#!/bin/bash

hook_name="$(basename -- "$0")"
cd "$(dirname "$0")/$hook_name.d"

for hook in *; do
  bash $hook
  RESULT=$?
  if [ $RESULT != 0 ]; then
    echo "Git Hooks: $hook_name.d/$hook hook exited with code $RESULT - push aborted."
    exit $RESULT
  fi
done

exit 0
