#!/bin/sh

branch=$(git branch --show-current)

cd "$(git rev-parse --show-toplevel)"

if ! npm run branch-name "$branch"; then
  printf "\nRename your branch\nIt should follow rules defined in .github/workflows/test.yml\n\n"
  exit 1
fi
